song_titles = {
    '21h-21.mp3': 'Kitsui - 21h21',
    'jtaff.mp3': "Kitsui Koni - J'taff",
    'ailleurs.wav': 'Koni - Ailleurs https://open.spotify.com/track/1ej1MFyhok597ohCn24x0Q?si=0ca1b7aa452840ea',
    '1er-couplet.wav': 'Koni - 1er couplet https://open.spotify.com/track/3O4lGTA2UiUvYLZjIGRRTT?si=5956fecd92884c43',
    'a-travers-les-gens.mp3': 'Kitsui Koni - À travers les gens',
    'anakin.mp3': 'Kitsui Koni - Anakin',
    'besoin-daide.mp3': "Kitsui Koni - Besoin d'aide https://open.spotify.com/track/5lB8V03QVazVN3LDEd96nX?si=17200cf453e04cff",
    'bon-endroit.wav': 'Kitsui Koni - Bon endroit https://open.spotify.com/track/476X6ywMJ0ouiG93OjJPR3?si=22cd02f95a33482f',
    'bro.mp3': 'Kitsui & Biaco - Bro https://open.spotify.com/track/42Wwxi75o3SUZPjDa7msAS?si=e4fca77399d94f4d',
    'cheat-code.mp3': 'Kitsui Koni - Cheat-code',
    'comme-dhab.mp3': "Kitsui Koni - Comme d'hab",
    'constats.wav': 'Kitsui Koni - Constats https://open.spotify.com/track/5IK4rnjQpUkA48Jywjkr2g?si=08b84097f3854ca8',
    'copier-coller.wav': 'Kitsui Koni - Copier coller https://open.spotify.com/track/427p3cWOLea7f8GwnOb3vW?si=119872a178124ae6',
    'dans-le-feu-les-flammes.wav': 'Kitsui Koni - Dans le feu les flammes https://open.spotify.com/track/421ENtpWZwzj3fNWbxnGCt?si=02e642092a0040b8',
    'dans-mon-coeur-ca-fait.wav': 'Koni - Dans mon coeur ça fait... https://open.spotify.com/track/6BRmfVcURIDULLJP2OZjXk?si=853f97686e0e4d16',
    'demain-la-veille.mp3': 'Kitsui Koni - Demain la veille',
    'demain.mp3': 'Kitsui Koni - Demain',
    'demi-coeur.mp3': 'Kitsui - Demi-coeur',
    'des-fois.mp3': 'Kitsui - Des fois https://open.spotify.com/track/6nV7AV65kfkPIEieOOCGyS?si=2090118b72894cb2    ',
    'drive-by.wav': 'Kitsui Koni - Drive-by https://open.spotify.com/track/0CzWpj3eUWFHcTf7OE7UK0?si=067bd7956c574200',
    'emprisonne.wav': 'Kitsui Koni - Emprisonné https://open.spotify.com/track/3K5Jky5CdH6OE7ApgLQWl8?si=df7a6277e5eb4738',
    'en-pleine-tempete.wav': 'Koni - En pleine tempête',
    'encore-seul.wav': 'Koni - Encore seul https://open.spotify.com/track/4Ynz0rfUU3kq2U1GGekMMI?si=2f62f53175804474',
    'est-ce-que-tes-triste.wav': "Koni - T'es triste ?? https://open.spotify.com/track/76ZEJo8NrrGmB79ieRP32Y?si=352727cabb5f41c7",
    'fais-le.mp3': 'Kitsui Koni - Fais-le',
    'flow.wav': 'Kitsui Koni - Flow https://open.spotify.com/track/0ioPInNuPoPlkOzC1Tt8De?si=3e87c9d3ffa6405e',
    'funk-vcg.wav': 'Kitsui Koni - Funk VCG https://open.spotify.com/track/1gufzDbekhBAqbeqxeWm6u?si=47b1454ed24a4da4',
    'heureux.wav': 'Koni - Heureux? https://open.spotify.com/track/5511qgse6acMXQwUo08lUV?si=2b3d4a0409f7483b',
    'italia.mp3': 'Kitsui Koni - Santa Catalina',
    'japprend-lequilibre.mp3': "Kitsui Koni - J'apprend l'équilibre",
    'jme-releve.mp3': "Kitsui (feat. Biaco) - J'me relève",
    'jsais-pas-tellement.wav': "Koni - J'sais pas tellement https://open.spotify.com/track/7MSItuUtov00jYAIsTNoDc?si=65ca2ea58dae480f",
    'koni-loupa.mp3': "Koni (feat. Loupa)",
    'late-night.mp3': "Kitsui Koni - Late night https://open.spotify.com/track/5YIe0g0bHfPXAWGZFhNn9u?si=64199a7f37384005",
    'maladie.wav': "Kitsui Koni - Maladie https://open.spotify.com/track/3ChaHH7yB4CTpP7EXZ0EhB?si=aa253720644e48a7",
    'mediator.mp3': "Kitsui Koni - Médiator",
    'meme-pas.wav': "Koni - Même pas https://open.spotify.com/track/5fKX7ejviSGKr8Qhn8uQe3?si=3bac51d16cae4083",
    'miss-moon.mp3': "Kitsui - Miss moon",
    'nul-part.wav': "Koni - Nul part https://open.spotify.com/track/3MKOmIIOVVcVcdiU808qe7?si=2e69c9946d34469c",
    'personne.mp3': "Kitsui - Personne https://open.spotify.com/track/7fWeGzgrbRmcA3y2WVg8vS?si=582577accfd74b25",
    'pleine-vitesse.wav': "Koni - Pleine vitesse https://open.spotify.com/track/52El1WmK5J1dt4w6M2e999?si=adfc85c0d2ef4984",
    'repondeur.wav': "Kitsui Koni - Répondeur https://open.spotify.com/track/15CdWoARhqSS5bOf4kPMPg?si=bb195f982203460d",
    'rose.wav': "Kitsui Koni - Rose https://open.spotify.com/track/2yLabHgDxev3SdRqOKhs0D?si=e6fedb9382a64f52",
    'sky.wav': "Kitsui Koni - Sky https://open.spotify.com/track/0fN9YHunlpnMmMfeKEL26w?si=66fd1557684c4494",
    'soleil.wav': "Kitsui Koni - Soleil https://open.spotify.com/track/5IFVfoKmDO2d4IimOzNDhf?si=57bf7db893f3433f",
    'tant-didees.mp3': "Kitsui Koni - Tant d'idées",
    'un-dces-4.wav': "Koni - Un d'ces 4 https://open.spotify.com/track/7LPVUZrs0gWoEkuPvqDPv9?si=8e67bea4c5de4436",
    'que-la-pluie.wav': "Koni - Que la pluie https://open.spotify.com/track/5ogQmIKhYohp3AAnWdrwGN?si=8a03023faee14239",
    'un-bon-moment.mp3': "Kitsui Koni - Un bon moment",
    'benzo.wav': "Koni - Benzo",
    'all-in.wav': "Koni - All in",
    'la-hollandaise.mp3': "Kitsui Koni - La hollandaise",
    'kennen.mp3': "Kitsui - Kennen",
    'la-hype.mp3': "Kitsui - La hype",
    'du-genre.mp3': "Koni - Du genre",
    'file.mp3': "Koni - File",
    'ya-un-moment.mp3': "Kitsui Koni - Y'a un moment",
    'biggy.mp3': "Kitsui Koni - Biggy",
    'jfume.mp3': "Koni - J'fume",
    'star-dans-les-yeuz.mp3': "Kitsui Koni - Star dans les yeuz",
    'alone.mp3': "Kitsui - Alone",
    'amigo.mp3': "Kitsui - Amigo",
    'happy-end.mp3': "Kitsui - Happy end",
    'window.mp3': "Kitsui - Window",
    'ivresse.mp3': "Koni - Ivresse",
    'la-pluie.mp3': "Kitsui - La pluie",
    'nostalgique.mp3': "Kitsui - Nostalgique",
    'solo.mp3': "Kitsui - Solo",
    'susano.mp3': "Kitsui - Susanô",
    'connerie.mp3': "Koni - Connerie",
    'different.mp3': "Koni - Différent",
    'gave.mp3': "Koni - Gavé",
    'millions.mp3': "Koni - Millions",
    'asap.mp3': "Kitsui - ASAP",
    'nul-part.mp3': "Koni - Nul part",
    'mango.mp3': "KItsui - Mango",
    'en-bateau.mp3': "Kitsui - En bateau",
    'arrete-de-penser.mp3': "Koni - Arrête de penser",
    'loin-de-la-terre.mp3': "Kitsui Koni - Loin de la terre",
    'depuis-petit.mp3': "Koni - Depuis petit",
    'dans-ma-ville.mp3': "Koni - Dans ma ville",
    'zero.mp3': "Koni - Zero",
    'le-temps-passe.mp3': "Koni - Le temps passe",
    'yellow-fruity-stripes.mp3': "Kitsui Koni - Yellow fruity stripes",
    'frero.mp3': "Koni - Frero",
    'fonsde.mp3': "Koni - Fonsdé",
    'cigarette.mp3': "Koni - Cigarette",
    'insomniaque.mp3': "Kitsui Koni - Insomniaque",
    'cest-pas-grave.mp3': "Kitsui Koni - C'est pas grave",
    'dans-les-nuages.mp3': "Kitsui Koni - Dans les nuages",
    'miroir.mp3': "Kitsui Koni - Miroir",
    'hier-soir.mp3': "Kitsui Koni - Hier soir",
    'uchiha.mp3': "Kitsui - Uchiha",
    'mon-x.mp3': "Kitsui - Mon X",
    'dope.mp3': "Kitsui Koni - Dope",
    'omg.mp3': "Kitsui - OMG!",
    'la-colombe.mp3': "Kitsui - La colombe",
    'sur-paris.mp3': "Kitsui - Sur Paris",
    'la-nuit.mp3': "Koni - La nuit",
    'rever.mp3': "Koni - Rêver",
    'pokemon-&-yugiho.mp3': "Kitsui Koni - Pokémon & Yu-gi-ho",
    'moche.mp3': "Kitsui - Moche",
    'cette-soiree.mp3': "Kitsui Koni - Cette soirée",
    'wouh-wouh.mp3': "Kitsui - Wouh wouh",
    'lvdr.mp3': "Kitsui Koni - LVDR",
    'le-temps-dune-barre.mp3': "Kitsui Koni - Le temps d'une barre",
    'akatsuki.mp3': "Kitsui & Biaco - Akatsuki",
    'perle.mp3': "Koni - Perle",
    'nindo.mp3': "Kitsui - Nindô",
    'gaara.mp3': "Kitsui Koni - Gaara",
    'la-passion.mp3': "Kitsui - La passion",
    'appart-44.mp3': "Kitsui - Appart 44",
    'orange-et-vert.mp3': "Kitsui - Orange et vert",
    'nuage.mp3': "Kitsui - Nuage",
    'loin.mp3': "Kitsui Koni - Loin",
    'p2.mp3': "Kitsui Koni - P2",
    'mysterio.mp3': "Kitsui Koni - Mystério",
    'le-canape.mp3': "Kitsui KOni & Lun - Le canapé",
    'en-scred.mp3': "Kitsui Koni - En scred",
    'the-bus.mp3': "Kitsui & Bastian - The bus",
    'amnesique.mp3': "Kitsui - Amnésique",
    'dior.mp3': "Kitsui & Roman - Dior",
    'ismael.mp3': "Kitsui - Ismaël",
    'melodie.mp3': "Kitsui - Mélodie",
    'niaks.mp3': "Kitsui - Niaks",
    'intro.mp3': "Kitsui - Intro",
}